# Generated by Django 5.2.6 on 2025-10-15 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('tipo', models.CharField(choices=[('LIBRO', 'Libro'), ('BIEN', 'Bien'), ('OTROS', 'Otros')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BienMaterial',
            fields=[
                ('recurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recursos.recurso')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_bien', models.CharField(choices=[('MOVIL', 'Móvil'), ('INMOVIL', 'Inmóvil')], max_length=10)),
                ('serie', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('REPARACION', 'En reparación'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=15)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad_total', models.PositiveIntegerField(default=1)),
                ('cantidad_disp', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('recurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recursos.recurso')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('editorial', models.CharField(blank=True, max_length=100)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad_total', models.PositiveIntegerField(default=1)),
                ('cantidad_disp', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
