# Generated by Django 5.2.6 on 2025-10-15 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='grado',
            options={'verbose_name': 'Grado', 'verbose_name_plural': 'Grados'},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'verbose_name': 'Nivel', 'verbose_name_plural': 'Niveles'},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
    ]
