# Generated by Django 5.2.6 on 2025-10-15 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_cuenta_options_alter_grado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grado',
            options={'verbose_name_plural': 'Grados'},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'verbose_name_plural': 'Niveles'},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name_plural': 'Turnos'},
        ),
    ]
