# Generated by Django 5.2.6 on 2025-10-15 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_grado_options_alter_nivel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name': 'Cuenta de Usuario', 'verbose_name_plural': 'Cuentas de Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Está Activo'),
        ),
        migrations.AlterField(
            model_name='grado',
            name='nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='usuarios.nivel', verbose_name='Nivel Educativo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grado',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Grado (e.g., 1°, 2°)'),
        ),
        migrations.AlterField(
            model_name='grado',
            name='seccion',
            field=models.CharField(max_length=10, verbose_name='Sección (e.g., A, B)'),
        ),
        migrations.AlterField(
            model_name='grado',
            name='turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='usuarios.turno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cuenta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='dni',
            field=models.CharField(max_length=15, unique=True, verbose_name='DNI/Identificación'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.grado', verbose_name='Grado/Aula Asignado'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
